- name: Play1
  hosts: all
  vars:
    action: guru
    URL:

  tasks:
   - name: Run this when the distribution is centos
     action: debug msg="{{ansible_distribution}}"
     when: ansible_distribution == "CentOS"

   - name: run this task when the action variable is declared
     action: debug msg="Action variable is declared"
     when: action is defined     #execute this task if action variable is defined    

   - name: run this task when the URL variable value is not declared
     action: debug msg="URL variable value is not declared"
     when: URL is not defined     #execute this task if action variable is not defined    