- name: demo on copy files
  hosts: all

  tasks:
   - name: copy the files from ansible server to remote servers
     ansible.builtin.copy:
      src: important.yml
      dest: /home/centos/
      owner: root
      group: root
      mode: '0644'
      
