- name: Demo on copy module
  hosts: all

  tasks:
    - name: Copy and keep backup of existing file
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: Hello.txt, dest: /home/centos/ }
        - { src: Hello2.txt, dest: /home/centos/ }


