- name: Demo on copy module
  hosts: all

  tasks:
    - name: Copy and keep backup of existing file
      ansible.builtin.fetch:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        flat: yes
        fail_on_missing: no
      loop:
        - { src: /home/centos/Hello1.txt, dest: /home/centos/ }
        - { src: /home/centos/Hello3.txt, dest: /home/centos/ }
      


