- name: Demo on file module
  hosts: all
  become: yes

  tasks: 
    - name: Ensure config file exists
      ansible.builtin.file:
        dest: /opt/redis
        state: directory
        recurse: yes
        owner: centos
        group: centos
        mode: '0755'
    