- name: Demo on file module
  hosts: all
  become: yes

  tasks: 
    - name: Create redis directory
      ansible.builtin.file:
        path: /opt/redis
        state: directory
        mode: '0755'
        owner: redis
        group: redis
    