- name: Play1
  hosts: all
  #gather_facts: No
  vars:
    URL: www.amazon.com
  vars_prompt:
    - name: URNAME
      prompt: Enter ur name
      private: false
  vars_files:
    - "{{ENV}}.yml"
    - "{{ENV1}}.yml"

  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: The task1 value is {{URL}}

    - name: Task2
      vars:
        URL: www.googlelocal.com
      ansible.builtin.debug:
        msg: The task2 value is {{URL}}

    - name: Task3
      ansible.builtin.debug:
        msg: The task2 value at run time {{NAME}}

    - name: Task4
      ansible.builtin.debug:
        msg: The task4 value from dev.yaml file {{INS_TYPE}}

    - name: Task5
      ansible.builtin.debug:
        msg: The task5 value from dev.yaml file {{INS_TYPE1}}
    
    - name: Task6                                       #for this task gather_facts should be yes
      ansible.builtin.debug:
        msg: The fact data is {{ansible_distribution}}

    - name: Task7                                       #for this task gather_facts should be yes
      ansible.builtin.debug:
        msg: The mac address is {{ansible_default_ipv4.macaddress}}

    - name: shell command uptime
      ansible.builtin.shell: uptime
      register: OUT

    - name: To print uptime 
      ansible.builtin.debug:
        msg: The uptime is {{OUT}}
    
    - name: To print the stdout of uptime
      ansible.builtin.debug:
        msg: The print the stdout of uptime {{OUT.stdout}}

    - name: declare a variable
      ansible.builtin.set_fact:
        EXITCODE: {{OUT.rc}}

    - name: Tp print the exit code of uptime
      ansible.builtin.debug:
        msg: {{EXITCODE}}