- name: Play1
  hosts: all

  tasks: 
    - name: Frontend
      ansible.builtin.debug:
        msg: This fronend
      tags: frontend
        
    - name: backend
      ansible.builtin.debug:
        msg: This backend
      tags: backend

    - name: DB
      ansible.builtin.debug:
        msg: This db
      tags: db

    


    

      

    

     


