- name: Creating users
  hosts: all
  become: yes

  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{item}}"
        state: absent
      loop:
        - vishal
        - venu
        - amar
        - tanvi
        - rithanya
        - vikram
      register: OUT

    - name: Print the OUT
      ansible.builtin.debug:
        msg: "The values are {{OUT}}"

      


    


    

      

    

     


