- name: create users
  hosts: all
  become: yes

  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{item}}"
        state: present
        msg: "The value of {{item}}"
      loop:
        - tanvi
        - rithanya
        - amar
      


    


    

      

    

     


