- name: create users
  hosts: all
  become: yes

  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{item}}"
        state: present
      loop:
        - tanvi
        - rithanya
        - amar
      register: user_result

    - name: Show message after user creation
      ansible.builtin.debug:
        msg: The details are "{{user_result}}"
      


    


    

      

    

     


