- name: Creating users
  hosts: all
  become: yes

  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        state: present
      loop:
        - { name: 'vikram', uid: 1005 } 
        - { name: 'vishal', uid: 1006 }
        - { name: 'venu', uid: 1007 }
      register: OUT

    - name: Print the OUT
      ansible.builtin.debug:
        msg: "The values are {{OUT}}"

      


    


    

      

    

     


