- name: Demo on Yum
  hosts: all
  become: yes
  tasks:
    - name: copy the files from ansible server to remote server
      ansible.builtin.copy:
        src: dev.yml
        dest: /home/centos/
        owner: root
        group: root
        backup: yes


    


    

      

    

     


