- name: Demo on Yum
  hosts: all
  become: yes

  tasks:
    - name: Install git, vim, wget
      ansible.builtin.package:
        name: "{{item}}"
        state: present
        update_cache: yes
        use: yum
      loop:
        - git
        - vim
        - wget
        - nginx
      register: OUT
   
    - name: COntent
      ansible.builtin.yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - vim
        - wget
        - nginx
      register: OUTPUT

    - name: To print the OUTPUT variable
      ansible.builtin.debug:
        msg: The content in "{{OUTPUT}}"
      


    


    

      

    

     


