- name: Demo on loop
  hosts: all
  become: yes
  tasks:
    - name: create user
      ansible.builtin.user:
        name: {{item.name}}
        uid: {{item.uid}}
      loop:
        - { name: 'ram', uid: 1009 }
        - { name: 'raja', uid: 1010 }
        - { name: 'laxman', uid: 1011 }
  


    


    

      

    

     


