- name: Demo on Yum
  hosts: all
  become: yes
  tasks:
    - name: copy the files from ansible server to remote server
      ansible.builtin.copy:
        dest: /home/centos/file2.txt
        content: "Hello in file2"


    


    

      

    

     


