- name: Demo on Yum
  hosts: all
  become: yes
  tasks:
    - name: copy the files from ansible server to remote server
      ansible.builtin.fetch:
        src: /home/centos/cost.txt
        dest: /home/centos/ansible
        backup: yes


    


    

      

    

     


