- name: Play1
  hosts: all
  vars:
    URL: www.google.com
  gather_facts: no

  tasks:
    - name: print the global variable
      ansible.builtin.debug: 
        msg: The value of GV is {{URL}}

    - name: Execute the uptime
      ansible.builtin.shell: uptime
      register: OUT

    - name: print the uptime
      ansible.builtin.debug: 
        msg: uptime is "{{OUT}}"

    - name: print the uptime stdout
      ansible.builtin.debug: 
        msg: uptime is "{{OUT.stdout}}"

     


