- name: Play1
  hosts: all
  vars:
    URL: www.google.com

  tasks:
    - name: print the global variable
      ansible.builtin.debug: 
        msg: The value of GV is {{URL}}

    - name: print the global variables
      ansible.builtin.debug: 
        msg: The value of GV is "{{ansible_distribution}}"
      
    - name: Printing the default variable
      ansible.builtin.debug:
        msg: mac address is "{{ansible_default_ipv4.macaddress}}"


