- name: Play1
  hosts: all
  vars:
    URL: www.google.com
  vars_prompt:
    - name: URNAME
      prompt: enter ur name

  tasks:
    - name: print the global variable
      ansible.builtin.debug: 
        msg: The value of GV is {{URL}}
    - name: The print the prompt var
      ansible.builtin.debug:
        msg: The prompt value is {{URNAME}}

    - name: print the global variable
      ansible.builtin.debug: 
        msg: The value of CLIV is {{NAME}}