- name: Play1
  hosts: all

  tasks: 
    - name: Frontend
      ansible.builtin.debug:
        msg: "The value of loop is {{item}}"
      loop:
        - 100
        - 200
        - 300


    


    

      

    

     


