- name: Play1
  hosts: all
  vars:
    URL: www.google.com
  gather_facts: no

  tasks:
    - name: print the global variable
      ansible.builtin.debug: 
        msg: The value of GV is {{URL}}

    - name: Execute the uptime
      ansible.builtin.shell: uptime
      register: OUT

    - name: print the uptime
      ansible.builtin.debug: 
        msg: uptime is "{{OUT}}"

    - name: print the uptime stdout
      ansible.builtin.debug: 
        msg: uptime is "{{OUT.stdout}}"
    
    - name: declare a variable
      ansible.builtin.set_fact:
        EXITCODE: "{{OUT.rc}}"

    - name: print the uptime rc
      ansible.builtin.debug: 
        msg: uptime is "{{EXITCODE}}"

    - name: shell command to check java process
      ansible.builtin.shell: ps -u centos | grep sshd
      register: OUTPUT
      ignore_errors: yes

    - name: print the OUTPUT content
      ansible.builtin.debug: 
        msg: The value of GV is {{OUTPUT}}
      

    

     


