- name: Demo on Service
  hosts: all
  become: yes

  tasks:
    - name: Ensure nginx is running and enabled at boot
      ansible.builtin.service:
       name: "{{ item }}"
       state: started
       enabled: yes
      
      loop:
        - chronyd
        - firewalld
        - rsyslog

  



