- name: Demo on Vars usage
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: Value of the URL is {{URL}}
        
    - name: Printing the variables names
      ansible.builtin.debug:
        msg: Value of the URL's is {{URL}}