- name: copy Centos base repo
  ansible.builtin.copy:
    src: CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    backup: yes

- name: Install NodeSource repo RPM
  become: true
  ansible.builtin.get_url:
    url: https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
    dest: /tmp/nodesource-release.rpm

- name: Add NodeSource repo
  become: true
  ansible.builtin.yum:
    name: /tmp/nodesource-release.rpm
    state: present

# Important: install nodejs (and npm if separate on your distro)
- name: Install Node.js (includes npm on NodeSource)
  become: true
  ansible.builtin.yum:
    name: nodejs         # harmless if npm already comes with nodejs; required on some distros
    state: present

- name: Crreate Application user
  ansible.builtin.user:
    user: "{{APPUSER}}"
    state: present

- name: unarchieve the folder
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/user/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name: cleanup
  ansible.builtin.file:
    path: /home/roboshop/user
    state: absent
  ignore_errors: yes

- name: copying
  ansible.builtin.copy:
    src: /tmp/user-main/
    dest: /home/roboshop/user/
    owner: roboshop
    group: roboshop
    remote_src: yes

- name: Install project dependencies (npm install)
  community.general.npm:
    path: /home/roboshop/user/ 

- name: Copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/user.service

- name: Start and enable the Catalogue
  ansible.builtin.systemd:
    name: user
    state: started
    enabled: yes
    daemon_reload: yes